spring:
  application:
    name: ArtifactsMmoClient
  datasource:
    url: jdbc:h2:./artifactsclientdb;AUTO_SERVER=TRUE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
