CREATE TABLE IF NOT EXISTS characters (
    name VARCHAR(255) PRIMARY KEY,
    account VARCHAR(255) NOT NULL,
    skin VARCHAR(50) NOT NULL,
    level INT NOT NULL,
    xp INT NOT NULL,
    max_xp INT NOT NULL,
    gold INT NOT NULL,
    speed INT NOT NULL,
    mining_level INT NOT NULL,
    mining_xp INT NOT NULL,
    mining_max_xp INT NOT NULL,
    woodcutting_level INT NOT NULL,
    woodcutting_xp INT NOT NULL,
    woodcutting_max_xp INT NOT NULL,
    fishing_level INT NOT NULL,
    fishing_xp INT NOT NULL,
    fishing_max_xp INT NOT NULL,
    weaponcrafting_level INT NOT NULL,
    weaponcrafting_xp INT NOT NULL,
    weaponcrafting_max_xp INT NOT NULL,
    gearcrafting_level INT NOT NULL,
    gearcrafting_xp INT NOT NULL,
    gearcrafting_max_xp INT NOT NULL,
    jewelrycrafting_level INT NOT NULL,
    jewelrycrafting_xp INT NOT NULL,
    jewelrycrafting_max_xp INT NOT NULL,
    cooking_level INT NOT NULL,
    cooking_xp INT NOT NULL,
    cooking_max_xp INT NOT NULL,
    alchemy_level INT NOT NULL,
    alchemy_xp INT NOT NULL,
    alchemy_max_xp INT NOT NULL,
    hp INT NOT NULL,
    max_hp INT NOT NULL,
    haste INT NOT NULL,
    critical_strike INT NOT NULL,
    wisdom INT NOT NULL,
    prospecting INT NOT NULL,
    attack_fire INT NOT NULL,
    attack_earth INT NOT NULL,
    attack_water INT NOT NULL,
    attack_air INT NOT NULL,
    dmg INT NOT NULL,
    dmg_fire INT NOT NULL,
    dmg_earth INT NOT NULL,
    dmg_water INT NOT NULL,
    dmg_air INT NOT NULL,
    res_fire INT NOT NULL,
    res_earth INT NOT NULL,
    res_water INT NOT NULL,
    res_air INT NOT NULL,
    x INT NOT NULL,
    y INT NOT NULL,
    cooldown INT NOT NULL,
    weapon_slot VARCHAR(255) NOT NULL,
    rune_slot VARCHAR(255) NOT NULL,
    shield_slot VARCHAR(255) NOT NULL,
    helmet_slot VARCHAR(255) NOT NULL,
    body_armor_slot VARCHAR(255) NOT NULL,
    leg_armor_slot VARCHAR(255) NOT NULL,
    boots_slot VARCHAR(255) NOT NULL,
    ring1_slot VARCHAR(255) NOT NULL,
    ring2_slot VARCHAR(255) NOT NULL,
    amulet_slot VARCHAR(255) NOT NULL,
    artifact1_slot VARCHAR(255) NOT NULL,
    artifact2_slot VARCHAR(255) NOT NULL,
    artifact3_slot VARCHAR(255) NOT NULL,
    utility1_slot VARCHAR(255) NOT NULL,
    utility1_slot_quantity INT NOT NULL,
    utility2_slot VARCHAR(255) NOT NULL,
    utility2_slot_quantity INT NOT NULL,
    bag_slot VARCHAR(255) NOT NULL,
    task VARCHAR(255) NOT NULL,
    task_type VARCHAR(255) NOT NULL,
    task_progress INT NOT NULL,
    task_total INT NOT NULL,
    inventory_max_items INT NOT NULL,
    cooldown_expiration TIMESTAMP WITH TIME ZONE NULL,
    version INT NOT NULL
);

CREATE TABLE IF NOT EXISTS INVENTORY_SLOTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    character VARCHAR(255) NOT NULL,
    slot INT NOT NULL,
    code VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    UNIQUE (character, slot)
);

CREATE TABLE IF NOT EXISTS ITEMS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    level INT NOT NULL,
    type VARCHAR(100) NOT NULL,
    subtype VARCHAR(100) NOT NULL,
    description CLOB NOT NULL,
    tradeable BOOLEAN NOT NULL,
    conditions_json CLOB NULL,
    effects_json CLOB NULL,
    craft_json CLOB NULL,
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS CHARACTER_ROUTINES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    character VARCHAR(255) NOT NULL,
    routine VARCHAR(255) NOT NULL,
    request_json CLOB NULL,
    UNIQUE (character)
);